[workspace]
members = [
  "faust-build", 
  "faust-types", 
  "faust-state",
  "examples/example-jack",
  "examples/example-dbmeter-jack", 
  "examples/example-ui-slint-jack", 
  "examples/example-f64", 
]
resolver="2"
