[workspace]
members = [
  "faust-build",
  "faust-json",
  "faust-macro",
  "faust-state",
  "faust-types",
  "faust-ui",
  "faust-xml",
  "examples/dsp-macro",
  "examples/file-f64",
  "examples/include-macro",
  "examples/minimal",
  "examples/jack-ui",
  "examples/template-file",
]
resolver="2"
