[package]
name = "faust-macro"
version = "0.1.0"
authors = ["olafklingt"]
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[lib]
proc-macro = true

[features]
debug = []

[dependencies]
faust-build = { git = "http://github.com/Frando/rust-faust.git" }
tempfile = "3.2.0"
