[package]
name = "faust-macro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[lib]
proc-macro = true

[features]
debug = []

[dependencies]
#jack = "0.7.0"
#rtrb = "0.1.3"
faust-build = { git = "http://github.com/Frando/rust-faust.git" }
tempfile = "3.2.0"
#regex = "1.10.5"