use faust_build::faust_arg::{FaustArg, FaustArgs2CommandArgs};
use faust_json::deserialize::FaustJson;
use proc_macro2::TokenStream;
use quote::{format_ident, quote};
use std::{
    fs::{self, File},
    io::BufReader,
    path::{Path, PathBuf},
    process::Command,
};
use syn::{parse_str, Ident};

fn generate_dsp_code(struct_name: &str, dsp_path: &str) -> proc_macro2::TokenStream {
    let args: Vec<FaustArg> = vec![
        FaustArg::default_lang(),
        FaustArg::default_timeout(),
        FaustArg::DebugWarnings,
        FaustArg::StructName(struct_name.to_string()),
        FaustArg::Json(),
        FaustArg::DspPath(PathBuf::from(dsp_path)),
    ];

    let mut faust = Command::new("faust");
    faust.args(args.to_command_args());
    let faust_result = faust.output().expect("Failed to execute faust");
    assert!(
        faust_result.status.success(),
        "faust compilation failed: {}",
        String::from_utf8(faust_result.stderr).unwrap()
    );
    let stderr = String::from_utf8(faust_result.stderr).unwrap();
    assert!(
        !stderr.contains("WARNING"),
        "Fail on warning in stderr: \n{}",
        stderr
    );

    let dsp_code: String =
        String::from_utf8(faust_result.stdout).expect("could not parse stdout from command");
    let dsp_code: proc_macro2::TokenStream =
        parse_str(&dsp_code).expect("Failed to parse generated by faust rust code into tokens");
    dsp_code
}

fn architecture(
    dsp_code: TokenStream,
    ui_code: TokenStream,
    ui_reexport: TokenStream,
    module_name: Ident,
    struct_name: Ident,
) -> proc_macro2::TokenStream {
    quote! {
        mod #module_name {
            #![allow(clippy::all)]
            #![allow(unused_parens)]
            #![allow(non_snake_case)]
            #![allow(non_camel_case_types)]
            #![allow(dead_code)]
            #![allow(unused_variables)]
            #![allow(unused_mut)]
            #![allow(non_upper_case_globals)]

            use faust_types::*;

            #dsp_code
            #ui_code
        }

        pub use #module_name::#struct_name;
        #ui_reexport
    }
}

fn get_ui_from_json(
    json_path: &Path,
    module_name: &Ident,
    struct_name: &Ident,
) -> (proc_macro2::TokenStream, proc_macro2::TokenStream) {
    let json_file = File::open(json_path).expect("Failed to open json file");
    let json_reader = BufReader::new(json_file);
    let faust_json: FaustJson = serde_json::from_reader(json_reader).unwrap_or_else(|err| {
        panic!("json parsing error: {}", err);
    });
    faust_json.ui(module_name, struct_name)
}

fn main() {
    println!("cargo:rerun-if-changed=dsp");
    let struct_name = "Volume";

    let dsp_code = generate_dsp_code(struct_name, "dsp/volume.dsp");

    let module_name = format_ident!("dsp");
    let struct_name = format_ident!("{}", struct_name);
    let (ui_code, ui_reexport) =
        get_ui_from_json(Path::new("dsp/volume.dsp.json"), &module_name, &struct_name);

    let template =
        architecture(dsp_code, ui_code, ui_reexport, module_name, struct_name).to_string();
    println!("{}", &template);
    let parsed: syn::File = syn::parse_file(&template)
        .unwrap_or_else(|err| panic!("syn failed with: {}", err.into_compile_error()));
    let pp = prettyplease::unparse(&parsed);
    fs::write("src/dsp.rs", pp).expect("failed to write to destination path");
}
